### ISSUE TITLE
Inspecting an offline player broken.

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO-Classic#13]
https://pastebin.com/raw/3ETJFt8w
Running on build 31 via: https://ci.ecocitycraft.com/job/McMMO-Classic/

**Comment by nossr50** [comment]
I thought t00thpick1 already fixed this

**Comment by andrewkm** [comment]
Nope, inspect is pretty badly screwed up.

**Comment by andrewkm** [comment]
It's also causing tons of weird ass issues such as:
https://i.imgur.com/r5jPNU4.png

Also the offline name you're trying to inspect dissappears from mctop until the player goes online.

**Comment by andrewkm** [comment]
When bobby joins back online, inspect and mctop work and show him back in the list:
https://i.imgur.com/zy0szCY.png

**Comment by andrewkm** [comment]
So basically using mctop on an offline player shoots the error, and then causes this:
https://i.imgur.com/nwtMVKR.png
invalid old username shit.

Also when bobbyblack logged off, I used inspect on him, and it once again shot error and made him go back to invalid:
https://i.imgur.com/QhYxoOR.png

oof :(

**Comment by t00thpick1** [comment]
On it.
