### ISSUE TITLE
Mining double drops broken.

### ISSUE THREAD

**Issue by selfslaughter** [mcMMO-Dev/mcMMO-Classic#21]
Mining double drops appear to be broken on 1.6.1-Snapshot builds. Everything works fine on the last stable release 1.6.0.

Re-tested today with the latest build (commit b483602) on a fresh 1.13.2 test server running paper v621.

Additionally, commit f0ebff4 appears to of changed the config section from "Double_Drops" to "Bonus_Drops" without changing the default config file.

Renaming the Double_Drops section to Bonus_Drops in the cfg, Which although it additionally re-creates the Double_Drops section appears to work for fixing herbalism/woodcutting double drops, But not for mining.

Thanks and Happy Easter. :)

**Comment by nossr50** [comment]
Thanks I'll look into this soon.

**Comment by selfslaughter** [comment]
Thanks, I see whats going on with mining now. It's only giving double drops with a silk touch pick.

With a normal pick you don't get any extra drops.

**Comment by nossr50** [comment]
Remove the bonus drops section from your config and test again

**Comment by selfslaughter** [comment]
Just tested again on a completely fresh test setup and same thing.

Mined 9 ore with a normal pick and got 9 diamond.
Mined 9 ore with a silk pick and got 27 diamond ore.

![Untitled](https://user-images.githubusercontent.com/12112089/56467768-80b07300-6466-11e9-9a45-5361fc3c5b04.png)

**Comment by nossr50** [comment]
@selfslaughter Okay I'll start up classic on my test server and see if I can reproduce.

**Comment by selfslaughter** [comment]
No need to rush, enjoy the holiday break. :)

**Comment by nossr50** [comment]
@selfslaughter Yeah its a bit odd this is only happening in classic, testing to see if I can reproduce now.

**Comment by nossr50** [comment]
Well its fixed now, delete your config.yml to regen or update its Bonus_Drops section manually

**Comment by selfslaughter** [comment]
Yeap, all good now. Thanks for your continued efforts on this.
Looking forward to seeing how 3.0 shapes up.  :)
