### ISSUE TITLE
SQLException: SSL Connection required, but not supported by server

### ISSUE THREAD

**Issue by sliverpix** [mcMMO-Dev/mcMMO-Classic#23]
Server is running spigot 1.14 build 101 after updating mcmmo to 1.6.1 we receive the following:

`12.05 18:18:56 [Server] Server thread/INFO [mcMMO] Enabling mcMMO v1.6.1
12.05 18:18:57 [Server] Server thread/ERROR [mcMMO] Location: sun.reflect.NativeConstructorAccessorImpl newInstance0 -2
12.05 18:18:57 [Server] Server thread/ERROR [mcMMO] SQLException: SSL Connection required, but not supported by server.
12.05 18:18:57 [Server] Server thread/ERROR [mcMMO] SQLState: 08001
12.05 18:18:57 [Server] Server thread/ERROR [mcMMO] VendorError: 0`
pastebin of log file [pastebin.com](https://pastebin.com/Qi7AVjMX)

This also stalls the ability to load player data and users to our server typically see a red error message stating this.

This issue was NOT present with 1.6.0 on spigot version 1.14 build 101
pastebin of log file [pastebin.com](https://pastebin.com/Skg4K7Gq)

If we do a clean install (DB and Plugin folder wiped) we still see the SSL error coming from the plugin. Again, mcmmo 1.6.1 on spigot server 1.14 build 101
pastebin of log file [pastebin.com](https://pastebin.com/u8URtEyC)

Other information:

- MySQL server version 5.1.73
- host doesnt allow access to config files thus we can not adjust DB server environment
- DB server version hasnt changed since mcmmo version 1.5.10 and no errors were seen then.
- SSL error is not present in mcmmo version 1.6.0 and all testing in-game has thus not far not produced the SSL error
- All testing done under spigot v1.14 build 101 (error was not seen in previous spigot version)
- testing was centered around SSL and Player Data loading and is contained to that parameter.
- Issues have been opened within the last year (mcmmo versions prior to 1.6.0) and closed with no explanation or support. (examples #3099 & #2965)

Thoughts/Conclusions:
The SSL error was NOT present in version 1.6.0 or in 1.5.10 and DB server has not changed. Although the Spigot server was updated to 1.14 the error is not present on mcmmo versions prior to 1.6.1. Thus there may be a versioning bug that slipped in or at least a missing "default" behavior for checking that an SSL connection exists to the DB server.

In most cases, SSL checking is not needed to a DB that works on the backend as the client is not able to reach it. Add to this, that SSL between Minecraft server and DB is typically not necessary and is "usually", but not in every case, recommended as it directly affects efficiency of game play.

We have reverted our DB tables and mcmmo version to 1.6.0 and hope that this **ISSUE does not get closed without appropriate follow through.** Its discouraging and disheartening to see reports closed without some kind of explanation, after all I, like so many others, dont mind paying for the resource, but i do take offense if software I pay for and/or donate to ignore reports. Ill leave it at that.

**Comment by t00thpick1** [comment]
Is Ssl set to false in your config.yml?

**Comment by t00thpick1** [comment]
I'll take the silence as a yes.
