### ISSUE TITLE
Error "BlockDropItemEvent"!

### ISSUE THREAD

**Issue by Pyario** [mcMMO-Dev/mcMMO-Classic#26]
Error by pickup Blocks!

Server Version: Spigot(Paper ) | 1.13.2 | Linux | Java 8

McmmoVersion: 1.6.1
Storage Methode: Default no Mysql

Description:
I thought first it was due to the existing "UserData" but when I deleted all the error is still!

Error:
https://pastebin.com/h5VtMfwc
`

**Comment by nossr50** [comment]
Update Spigot to solve this

Run build tools with this command

java -jar BuildTools.jar --rev 1.13.2
