### ISSUE TITLE
McMMO not working

### ISSUE THREAD

**Issue by iSpexGaming** [mcMMO-Dev/mcMMO-Classic#29]
The McMMO plugin seems to be added and partially working, but abilities do not work and XP is not being gained. The chat does not give me an error but upon looking in the console I receive these messages.

> 06.06 17:30:45 [Server] ERROR [mcMMO] Plugin mcMMO v1.6.1 has failed to register events for class com.gmail.nossr50.listeners.BlockListener because org/bukkit/event/block/BlockDropItemEvent does not exist.
06.06 17:30:45 [Server] ERROR [mcMMO] Plugin mcMMO v1.6.1 has failed to register events for class com.gmail.nossr50.listeners.EntityListener because org/bukkit/event/entity/EntityTransformEvent does not exist.

**Comment by nossr50** [comment]
@iSpexGaming 

You need to update Spigot

If you type /version you'll see that you're out of date

Read BuildTools guide for info on how to update your Spigot

https://www.spigotmc.org/wiki/buildtools/#what-is-it
