### ISSUE TITLE
New blocks trigger interaction events

### ISSUE THREAD

**Issue by ArtelGG** [mcMMO-Dev/mcMMO-Classic#33]
New blocks, such as the grindstone and sweet berry bushes trigger ability interaction events (e.g. unarmed) when interacting with them. Shouldn't these be ignored similar to how the chests are?

**Comment by nossr50** [comment]
That's a good point, it will be done.

**Comment by t00thpick1** [comment]
Fixed https://github.com/mcMMO-Dev/mcMMO-Classic/commit/b0e7a4624f23383f59ec6545c2c4b549e82104a6

**Comment by ArtelGG** [comment]
Just to touch on this again, shouldn't iron and gold blocks also be on the list?

**Comment by t00thpick1** [comment]
why would they?

**Comment by ArtelGG** [comment]
Because they're used for other purposes. Iron block repairs, gold block salvages. Having it constantly ready/unready whilst repairing tools seems unnecessary to me.

**Comment by t00thpick1** [comment]
Thats fair.  On it
