### ISSUE TITLE
Mcmmo Classic 1.14

### ISSUE THREAD

**Issue by megacade** [mcMMO-Dev/mcMMO-Classic#37]
Is Mcmmo Classic compatible with MC version 1.14+? I bought it yet it, downloaded version. 1.6 (most recent build) but it doesn't work. It works in my 1.12.2 server (same build version) but not 1.14.

**Comment by DutchUser** [comment]
Please give us the server startup logs.

**Comment by nossr50** [comment]
You need to update Classic for it to work on 1.14
