### ISSUE TITLE
Cannot add task while iterating timers!

### ISSUE THREAD

**Issue by SauFey** [mcMMO-Dev/mcMMO-Classic#41]
https://pastebin.com/85gW4rM1

**Comment by electronicboy** [comment]
1) Wrong repo
2) Update

**Comment by SauFey** [comment]
What do you mean?

**Comment by electronicboy** [comment]
You're reporting an issue with the newer version of mcmmo on the issue
tracker for the classic version, this is also an issue which has been
resolved since you last updated
