### ISSUE TITLE
Commands like /mctop and /mcrank are not updating

### ISSUE THREAD

**Issue by NatsuoIshido** [mcMMO-Dev/mcMMO-Classic#46]
I have recently purchased McMMO for a 1.14 Spigot server, however I noticed that the command /mctop only updates when I reset the server, and that /mcrank is not updating at all. I am concerned as to if this means that the skills are not updating, thus their benefits for leveling are not applying. I had leveled up Acrobatics skill from level 1 to 50 before resetting and never rolled during the process, however after resetting on my 9th fall I rolled.

**Comment by t00thpick1** [comment]
Are you running with flatfile or mysql?

**Comment by NatsuoIshido** [comment]
I do not see flatfile (unless its a plugin, in that case no I do not) and MySQL requires an upgrade to the server.

**Comment by NatsuoIshido** [comment]
I see that after ~40 minutes to an hour of waiting they update. Perhaps I just wasn't waiting because I thought it updated instantly

**Comment by nossr50** [comment]
In a 20TPS server it should update every 10 minutes.
