### ISSUE TITLE
Smelting in regular furnaces does not yield mcmmo Mining XP

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO-Classic#53]
Can you please check this out for classic:
https://ecocitycraft.com/forum/threads/bug-smelting-in-regular-furnaces-does-not-yield-mcmmo-mining-xp.192546/

**Comment by t00thpick1** [comment]
I spun up my test server and I'm not seeing this, can you provide any additional info/verify this behavior?

**Comment by andrewkm** [comment]
Looks like I was totally wrong here, apologies.
