### ISSUE TITLE
Mining XP prison server

### ISSUE THREAD

**Issue by minemalia** [mcMMO-Dev/mcMMO-Classic#65]
Hey,

I am using the MCMMO plugin in my prison server, however I and my players do not gain mining experience.
In my survival server everything is fine, however in prison it doesn't work properly. I tried to use the default configuration, but this didn't fix the issue neither.

Mcmmo 1.6.2-SNAPSHOT
worldguard 7.0.2-SNAPSHOT;bf2593e (latest stable build on bukkit)
worldedit 7.1.0;8e55131 (latest stable build on bukkit)
Paper 1.15.2, build 282. (latest)

How can I fix this problem?

Kind regards,

**Comment by t00thpick1** [comment]
My first thought would be a permissions issue.  Barring that, potentially a
plugin conflict, especially with the way many prison servers interact with
blocks.   So first check your permissions, if those are correct, please let
me know what plugins you run.

**Comment by minemalia** [comment]
Thank you for your help, I figured out that this was caused by autosell.

I had to change the block_listener_priority in the autosell configuration to MONITOR instead of HIGHEST.
