### ISSUE TITLE
mctop Placeholders

### ISSUE THREAD

**Issue by sirblazzit** [mcMMO-Dev/mcMMO-Classic#91]
Would it be possible to add a placeholder such as %mcmmo_mctop_<rank>% that gives the username of the player with the highest power level? I want to create a NPC Podium for the mctop players, but I can't seem to find a way to do it.

**Comment by Chew** [comment]
Original issue for posterity:

> Would it be possible to add a placeholder such as %mcmmo_mctop_% that gives the username of the player with the highest power level? I want to create a NPC Podium for the mctop players, but I can't seem to find a way to do it.
